### ISSUE TITLE
[FR]天气预警推送关键词屏蔽

### ISSUE THREAD

**Issue by huuhghhgyg** [zxbmmmmmmmmm/FluentWeather#15]
- Windows版本: Windows 10 19045.3636
 - 应用版本: 0.0.15.0

**功能内容**
天气预警推送中能否添加屏蔽关键词的功能？

有时候有些预警信息没有什么帮助却总是推送会造成一定的困扰。比如我所在地区经常发布海上气象预警，但是和我却没有什么关系。如图：

![image](https://github.com/zxbmmmmmmmmm/FluentWeather/assets/10482172/1f956ed8-2a6c-4f22-b2d6-40bd7f10366a)

**实现方法**
可能可以使用正则表达式或直接匹配关键词过滤需要推送的通知？

**Comment by zxbmmmmmmmmm** [comment]
会在下个版本添加
