### ISSUE TITLE
[FR]启动时的加载界面

### ISSUE THREAD

**Issue by MSEDGE-CORE** [zxbmmmmmmmmm/FluentWeather#6]
当前样式：
SplashScreen后直接显示空白的天气页面模板
![屏幕截图 2023-10-04 154023](https://github.com/zxbmmmmmmmmm/FluentWeather/assets/74437699/a3f1fd54-1326-4870-b9d3-4b2d896b1cb6)

建议样式：
在获取/读取天气时
`<muxc:ProgressRing Name="WeatherProgressRing" IsActive="True" Width="64" Height="64" Visibility="Visible" HorizontalAlignment="Center" VerticalAlignment="Center" />`
`MainGrid.Visibility = Visibility.Collpased;`
完成后
`WeatherProgressRing.Visibility = Visibility.Collpased; `
`MainGrid.Visibility = Visibility.Visible;`

**Comment by zxbmmmmmmmmm** [comment]
在加载速度较快的情况下，ProcessRing可能过于突兀
以后可能会采用类似于Microsoft Store的骨架屏

**Comment by zxbmmmmmmmmm** [comment]
暂时先用一下ProgressRing好了（
以后可能会改

**Comment by zxbmmmmmmmmm** [comment]
https://github.com/zxbmmmmmmmmm/FluentWeather/assets/96322503/2d70e91c-80b2-489c-a54c-e31816af1ec3

这个怎么样(录屏有点卡)
